serviceMonitor:
  # enabled determines whether a serviceMonitor should be deployed
  enabled: true
trivy:
  # ignoreUnfixed is the flag to show only fixed vulnerabilities in
  # vulnerabilities reported by Trivy. Set to true to enable it.
  ignoreUnfixed: true
operator:
  # metricsVulnIdEnabled the flag to enable metrics about cve vulns id
  # be aware of metrics cardinality is significantly increased with this feature enabled.
  metricsVulnIdEnabled: true
  metricsClusterComplianceInfo: true
compliance:
  # cron this flag control the cron interval for compliance report generation
  cron: 0 */1 * * *
  # reportType this flag control the type of report generated (summary or all)
  reportType: summary
