apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 31110
