apiVersion: v1
kind: Pod
metadata:
  name: node-server
spec:
  containers:
    - name: node-server-container
      image: 952910/node-server
      ports:
        - containerPort: 7000
        - containerPort: 7001
