apiVersion: v1
kind: Service
metadata:
  name: node-server-service
spec:
  type: NodePort
  selector:
    app: node-server
  ports:
    - name: http
      port: 7000
      targetPort: 7000
      nodePort: 30100
    - name: http2
      port: 7001
      targetPort: 7001
      nodePort: 30101
