{
 "title": "CIS FINALIZED",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align:center;font-size:250%;font-weight:bold;color:#000;background-color:#146C94\">Kube Bench & Trivy Dashboard</p>"
   }
  },
  {
   "title": "KUBE BENCH CIS 1.20",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.Totals" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "KUBE BENCH CIS 1.20",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.Totals" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "KUBE BENCH CIS 1.20",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.Controls[*].tests[*]" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "KUBE BENCH CIS 1.20",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.Totals" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Trivy Cluster Compliance Report (CIS 1.23)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.summary" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "<p style=\"font-size:200%;font-weight:bold;color:#000;background-color:#FFFF\">Image Vulnerabilities</p>"
   }
  },
  {
   "title": "LOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Low\", namespace=~\"monitoring\"})"
    }
   ]
  },
  {
   "title": "MEDIUM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Medium\", namespace=~\"monitoring\"})"
    }
   ]
  },
  {
   "title": "HIGH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"High\", namespace=~\"monitoring\"})"
    }
   ]
  },
  {
   "title": "CRITICAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\", namespace=~\"monitoring\"})"
    }
   ]
  },
  {
   "title": "UNKNOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Unknown\", namespace=~\"monitoring\"})"
    }
   ]
  },
  {
   "title": "TOTAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{namespace=~\"monitoring\"})"
    }
   ]
  },
  {
   "title": "Image by CVE",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(trivy_vulnerability_id{namespace=~\"monitoring\"}) without (instance, job, endpoint, service, container)"
    }
   ]
  },
  {
   "title": "KUBE BENCH CIS 1.20",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.Controls[*].tests[*]" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "KUBE BENCH CIS 1.20 RESULTS",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.Controls[*].tests[*].results[*]"
      }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Kube Bench CIS 1.20 TESTS",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 44 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.Controls[*].tests[*]" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Trivy Cluster Compliance Report (CIS 1.23)",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 44 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.detailReport.results[*]" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  }
 ]
}