{
 "title": "CIS FINALIZED",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align:center;font-size:250%;font-weight:bold;color:#fff;background-color:#8569FF\">TRIVY DASHBOARD</p>"
   }
  },
  {
   "title": "Status - CIS Benchmarks",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trivy_cluster_compliance{container=\"trivy-operator\", title=\"CIS Kubernetes Benchmarks v1.23\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status - CIS Benchmarks",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trivy_cluster_compliance{container=\"trivy-operator\", title=\"CIS Kubernetes Benchmarks v1.23\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Severity - CIS Benchmarks",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (severity) (trivy_compliance_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Severity - CIS Benchmarks",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (severity) (trivy_compliance_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "<p style=\"font-size:200%;font-weight:bold;color:#000;background-color:#C38FFF\">Image Vulnerabilities</p>"
   }
  },
  {
   "title": "Image Vulnerability",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (severity) (trivy_image_vulnerabilities{severity=\"Low\", namespace=~\"$namespace\"})\n    or\n  sum by (severity) (trivy_image_vulnerabilities{severity=\"Medium\", namespace=~\"$namespace\"})\n    or\n  sum by (severity) (trivy_image_vulnerabilities{severity=\"High\", namespace=~\"$namespace\"})\n    or\n  sum by (severity) (trivy_image_vulnerabilities{severity=\"Critical\", namespace=~\"$namespace\"})\n)\n"
    }
   ]
  },
  {
   "title": "LOW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Low\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "MEDIUM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Medium\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "HIGH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"High\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "CRITICAL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Image by CVE",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(trivy_vulnerability_id{namespace=~\"$namespace\"}) without (instance, job, endpoint, service, container)"
    }
   ]
  },
  {
   "title": "UNKNOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Unknown\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "TOTAL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Trivy - CIS Benchmarks",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "trivy_compliance_info{title=\"CIS Kubernetes Benchmarks v1.23\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trivy",
   "type": "bargauge",
   "gridPos": { "h": 52, "w": 24, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trivy_compliance_info{title=\"CIS Kubernetes Benchmarks v1.23\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trivy Cluster Compliance Report (CIS 1.23)",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 85 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.detailReport.results[*]" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  }
 ]
}