apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service-1
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 7000
      nodePort: 30000
  selector:
    app: nodeapp
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service-2
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 7001
      nodePort: 30001
  selector:
    app: nodeapp
